### ISSUE TITLE
problem with build

### ISSUE THREAD

**Issue by mrAyaz** [skybrush-io/live#10]
hello. thanks for the open source project. I have a question. I can run the program with the help of the command (npm run start:electron) but I can’t build yo electron EXE for it run on another computer

**Comment by ntamas** [comment]
You can use any of the [standard Electron packaging tools](https://www.electronjs.org/docs/latest/tutorial/application-distribution#with-tooling). Unfortunately we cannot offer support for building packaged, ready-to-use executables of Skybrush as part of the community support package. You can download a pre-compiled executable of the community edition of the server, Live and most other components from https://skybrush.io/ - these come with limitations in the number of drones that you can connect to at the same time. If you would like to lift the limitations or you are building your own version of Skybrush with modifications, you can contact us via email or through the contact form of the homepage to subscribe for premium support.
