### ISSUE TITLE
Add hotkey for the "broadcast" switch on the UAV toolbar

### ISSUE THREAD

**Issue by ntamas** [skybrush-io/live#14]
Experience from last night's show: it would be very convenient to assign a hotkey to the "broadcast" switch on the UAV toolbar. Right now the easiest way to broadcast a "flash lights" signal (which is very useful to test whether the communication is good to all drones) is to use the _mouse_ to toggle the broadcast switch, then the _keyboard_ to press `W` to toggle the "flash lights" command. It would be much more convenient with `B W`, or maybe `Cmd-B W` (`Ctrl-B W` on Windows). I'm slightly leaning towards the `Cmd-B` variant to toggle the switch because it makes it harder to accidentally turn on broadcast mode (Cmd and B are relatively far away on the keyboard).

**Comment by vasarhelyi** [comment]
I also vote for Cmd-B instead of pure B.

**Comment by Isti115** [comment]
This has been implemented in ff355badf1719f5c08550b697a8fe2b8fef51ce0.
