### ISSUE TITLE
Blue trajectory line should be visible on the map even if there is no drone assigned to the trajectory slot

### ISSUE THREAD

**Issue by ntamas** [skybrush-io/live#2]
*Steps to reproduce*:

1. Open a show file in Live
2. Go to the UAVs list, turn on "Sort by mission IDs" in the header to see the empty slots for unassigned drones
3. Clear the show mapping so no drone should be assigned to any of the slots
4. Click on an empty slot in the "Assigned UAVs" section

*Expected result*:

The trajectory corresponding to the slot should be visible on the map even if no drone is assigned to the slot.

*Observed result*:

The trajectory line becomes visible only if you assign a drone to the slot (even if the drone does not exist in practice).

This might not be trivial to fix because the selection consists of a set of drone IDs and thus the selection is basically empty when you select an empty slot.

**Comment by Isti115** [comment]
Fixed in 1976fda6e2d66f19202c8c8b5f12db442f77a6b7 and 31b24cb9e07d53e48555565c58facb5f16e8be22.
