### ISSUE TITLE
Add a control window when the Turn Off button is pressed within SkyBrush Live , to prevent unexpected situations

### ISSUE THREAD

**Issue by DavideLentini** [skybrush-io/live#23]
With the recent developments of a system for a remote on/off , I believe it is critical to add a control window within Sky Brush Live when pressing the Turn Off button .

A control window that allows you to cancel sending the Turn Off command in broadcast , or to confirm it . 

It might also be useful to add this control window also when pressing the Sleep or Wake Up command , but we have confirmed that the latter messages(wake up and sleep )are ignored if the drone is armed , so I do not think it is fully necessary . 

Thanks all !

**Comment by DavideLentini** [comment]
Hi !
It would be great to have this option in the next version of Live . I find it very important for fleet safety . Thank you

**Comment by ntamas** [comment]
Sorry, I haven't forgotten about this but I couldn't squeeze this into 2.8.0. I'll try to get this done before the next minor release.

**Comment by ntamas** [comment]
Going through the issue tracker to clean things up. This is implemented in version 2.8.0 -- see attached screenshot.

<img width="629" alt="Screenshot 2024-01-02 at 11 11 02" src="https://github.com/skybrush-io/live/assets/195637/4255b646-3beb-4d04-95bc-42fd88116a7c">

**Comment by DavideLentini** [comment]
Thanks @ntamas I appreciate it very much . happy new year
