### ISSUE TITLE
Control panels are blocked by "SHOW AUTHORIZED TO START" button.

### ISSUE THREAD

**Issue by kazogihara** [skybrush-io/live#38]
Hello.
I would like to mention an issue, a small one on the screen display, that I have been wondering about.

### Steps to reproduce
1. Make "Show control" so small in height that control panels will not fit.
2. Click "SHOW AUTHORIZED TO START" button.
3. Scroll down to the bottom of the control panel.

### Expected result
* It would be nice if the "SHOW AUTHORIZED TO START" buttons did not block the control panel below.

### Additional information
1. Commit Hash
    * 95249aa5
2. Browser
    * Chrome 118.0.5993.71
3. image
![image](https://github.com/skybrush-io/live/assets/33021308/8bbcb224-20b1-4de7-9587-70713e2f17ec)

**Comment by Owais-Iqbal4** [comment]
Who are you ?

**Comment by ntamas** [comment]
I've made some adjustments to the layout in adba06a7; in particular, the visual glitch that you made a screenshot of does not happen any more and the "Show authorized to start" button stays attached to the bottom of the panel. I've also decreased the line height in the large colored buttons so there is less space between the icon and the label, allowing the buttons to fit better when the space is limited.

The "Show authorized to start" button will nevertheless stay on top of the button panel - that was a conscious design decision. What has changed now is that the upper part of the panel holding the large colored buttons is scrollable while it allows the "Show authorized to start" button to stay attached to the bottom of the panel.

Please give it a go and let me know whether this fixes your probem.

**Comment by Owais-Iqbal4** [comment]
I don't know why I am receiving these messages ?

**Comment by ntamas** [comment]
You are getting these messages because you are probably subscribed to all issues submitted to this Github repo:

https://github.com/skybrush-io/live

Please unsubscribe from the repo if you are not interested in these messages. Note that if you reply to this email, your response will be posted publicly under the issue to which you are responding to:

https://github.com/skybrush-io/live/issues/38

T.

------- Original Message -------

**Comment by Owais-Iqbal4** [comment]
Thank you so much to inform this.

**Comment by kazogihara** [comment]
Thanks for rapid reply!
As you said, this has already been resolved.
![image](https://github.com/skybrush-io/live/assets/33021308/f4b4501e-7976-4964-b45f-90025724a369)

**Comment by kazogihara** [comment]
If I have an Issue, should I post it on git hub? Or is it better to post it on the discord?
