### ISSUE TITLE
Adjustable contrast for the clocks LED display

### ISSUE THREAD

**Issue by ntamas** [skybrush-io/live#8]
On some displays, the contrast between the active and the inactive segments of the simulated LED display on the Clocks panel is not high enough. We should provide a slider or at least some preset options to enhance the contrast.

**Comment by Isti115** [comment]
Added an option to entirely disable the display of inactive segments in https://github.com/skybrush-io/live/commit/76e7ad36a152856eee10f6c9cb8f9fafe3cc216b.
